import React from 'react';
import { 
  PieChart, 
  BarChart2, 
  Calendar, 
  TrendingUp, 
  TrendingDown, 
  PiggyBank, 
  Layers,
  RefreshCw
} from 'lucide-react';
import useReportController from '../controllers/useReportController';

export function ReportsView({ onNotify }) {
  // Dispatches to UI Controller
  const {
    dashboardData,
    monthlyData,
    categoryData,
    loading,
    activeTab,
    selectTab,
    refreshReports,
  } = useReportController({ onNotify });

  const formatCurrency = (val) => {
    return new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(val || 0);
  };

  // Find max monthly amount for proportional bar chart
  const maxMonthly = monthlyData.reduce((max, item) => Math.max(max, Number(item.totalAmount || 0)), 0) || 1;
  const totalCatExpenses = categoryData.reduce((sum, item) => sum + Number(item.totalAmount || 0), 0) || 1;

  return (
    <div style={{ animation: 'fadeIn 0.25s ease-out' }}>
      {/* Header */}
      <div style={{
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: '24px',
        flexWrap: 'wrap',
        gap: '16px',
      }}>
        <div>
          <h1 style={{ fontSize: '1.85rem', color: '#FFFFFF', marginBottom: '4px' }}>
            Financial Intelligence & Reports
          </h1>
          <p style={{ fontSize: '0.86rem', color: 'var(--text-secondary)' }}>
            Deep analytics generated by backend reporting algorithms.
          </p>
        </div>
        <div style={{ display: 'flex', gap: '10px' }}>
          <button 
            className="btn btn-secondary"
            onClick={refreshReports}
            disabled={loading}
          >
            <RefreshCw size={15} />
            <span>Refresh Analytics</span>
          </button>
        </div>
      </div>

      {/* Tab Navigation - Controlled by UI Controller */}
      <div style={{
        display: 'flex',
        gap: '8px',
        marginBottom: '26px',
        borderBottom: '1px solid var(--border-subtle)',
        paddingBottom: '12px',
      }}>
        {[
          { id: 'overview', label: 'Summary Overview', icon: PieChart },
          { id: 'monthly', label: 'Monthly Trends', icon: BarChart2 },
          { id: 'categories', label: 'Category Allocation', icon: Layers },
        ].map((tab) => {
          const Icon = tab.icon;
          const isActive = activeTab === tab.id;
          return (
            <button
              key={tab.id}
              onClick={() => selectTab(tab.id)}
              style={{
                display: 'flex',
                alignItems: 'center',
                gap: '8px',
                padding: '8px 18px',
                borderRadius: 'var(--radius-sm)',
                border: 'none',
                background: isActive ? 'var(--accent-primary)' : 'rgba(255, 255, 255, 0.04)',
                color: isActive ? '#FFFFFF' : 'var(--text-secondary)',
                fontWeight: isActive ? 600 : 500,
                fontSize: '0.85rem',
                cursor: 'pointer',
                transition: 'var(--transition)',
              }}
            >
              <Icon size={16} />
              <span>{tab.label}</span>
            </button>
          );
        })}
      </div>

      {/* Tab Content */}
      {activeTab === 'overview' && dashboardData && (
        <div style={{ display: 'flex', flexDirection: 'column', gap: '24px' }}>
          <div style={{
            display: 'grid',
            gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))',
            gap: '20px',
          }}>
            <div className="glass-panel" style={{ padding: '24px' }}>
              <span style={{ fontSize: '0.82rem', fontWeight: 600, color: 'var(--text-muted)' }}>CUMULATIVE INCOME</span>
              <div style={{ fontSize: '1.9rem', fontWeight: 700, color: 'var(--color-success)', marginTop: '8px' }}>
                {formatCurrency(dashboardData.totalIncome)}
              </div>
            </div>
            <div className="glass-panel" style={{ padding: '24px' }}>
              <span style={{ fontSize: '0.82rem', fontWeight: 600, color: 'var(--text-muted)' }}>CUMULATIVE EXPENSES</span>
              <div style={{ fontSize: '1.9rem', fontWeight: 700, color: 'var(--color-danger)', marginTop: '8px' }}>
                {formatCurrency(dashboardData.totalExpense)}
              </div>
            </div>
            <div className="glass-panel" style={{ padding: '24px' }}>
              <span style={{ fontSize: '0.82rem', fontWeight: 600, color: 'var(--text-muted)' }}>NET SAVINGS ACCUMULATED</span>
              <div style={{ fontSize: '1.9rem', fontWeight: 700, color: 'var(--accent-primary)', marginTop: '8px' }}>
                {formatCurrency(dashboardData.netSavings)}
              </div>
            </div>
          </div>
        </div>
      )}

      {activeTab === 'monthly' && (
        <div className="glass-panel" style={{ padding: '28px' }}>
          <h3 style={{ fontSize: '1.2rem', color: '#FFFFFF', marginBottom: '6px' }}>Monthly Expense Timeline</h3>
          <p style={{ fontSize: '0.82rem', color: 'var(--text-secondary)', marginBottom: '28px' }}>
            Historical spending distribution across billing periods.
          </p>

          {monthlyData.length === 0 ? (
            <div style={{ padding: '40px', textAlign: 'center', color: 'var(--text-muted)' }}>
              No monthly breakdown data available yet.
            </div>
          ) : (
            <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
              {monthlyData.map((item, idx) => {
                const percentage = Math.min(100, Math.round((Number(item.totalAmount) / maxMonthly) * 100));
                return (
                  <div key={idx} style={{ display: 'flex', flexDirection: 'column', gap: '6px' }}>
                    <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.84rem' }}>
                      <span style={{ fontWeight: 600, color: 'var(--text-primary)' }}>{item.month}</span>
                      <span style={{ fontWeight: 700, color: 'var(--color-danger)' }}>{formatCurrency(item.totalAmount)}</span>
                    </div>
                    <div style={{
                      width: '100%',
                      height: '10px',
                      borderRadius: 'var(--radius-full)',
                      background: 'rgba(255, 255, 255, 0.05)',
                      overflow: 'hidden',
                    }}>
                      <div style={{
                        width: `${percentage}%`,
                        height: '100%',
                        borderRadius: 'var(--radius-full)',
                        background: 'linear-gradient(90deg, #6366F1, #EC4899)',
                        transition: 'width 0.6s cubic-bezier(0.16, 1, 0.3, 1)',
                      }} />
                    </div>
                  </div>
                );
              })}
            </div>
          )}
        </div>
      )}

      {activeTab === 'categories' && (
        <div className="glass-panel" style={{ padding: '28px' }}>
          <h3 style={{ fontSize: '1.2rem', color: '#FFFFFF', marginBottom: '6px' }}>Category Allocation Breakdown</h3>
          <p style={{ fontSize: '0.82rem', color: 'var(--text-secondary)', marginBottom: '28px' }}>
            Proportional breakdown of where capital is deployed.
          </p>

          {categoryData.length === 0 ? (
            <div style={{ padding: '40px', textAlign: 'center', color: 'var(--text-muted)' }}>
              No category breakdown records available.
            </div>
          ) : (
            <div style={{
              display: 'grid',
              gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))',
              gap: '16px',
            }}>
              {categoryData.map((cat, idx) => {
                const pct = Math.round((Number(cat.totalAmount) / totalCatExpenses) * 100) || 0;
                return (
                  <div
                    key={idx}
                    style={{
                      padding: '18px',
                      borderRadius: 'var(--radius-md)',
                      background: 'rgba(255, 255, 255, 0.02)',
                      border: '1px solid rgba(255, 255, 255, 0.05)',
                      display: 'flex',
                      flexDirection: 'column',
                      justifyContent: 'space-between',
                    }}
                  >
                    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '10px' }}>
                      <span style={{ fontWeight: 600, fontSize: '0.92rem', color: '#FFFFFF' }}>{cat.categoryName}</span>
                      <span className="badge badge-info">{pct}% of total</span>
                    </div>
                    <div style={{ fontSize: '1.25rem', fontWeight: 700, color: 'var(--color-danger)', marginBottom: '12px' }}>
                      {formatCurrency(cat.totalAmount)}
                    </div>
                    <div style={{
                      width: '100%',
                      height: '6px',
                      borderRadius: 'var(--radius-full)',
                      background: 'rgba(255, 255, 255, 0.05)',
                      overflow: 'hidden',
                    }}>
                      <div style={{
                        width: `${pct}%`,
                        height: '100%',
                        borderRadius: 'var(--radius-full)',
                        background: 'linear-gradient(90deg, #F43F5E, #FB7185)',
                      }} />
                    </div>
                  </div>
                );
              })}
            </div>
          )}
        </div>
      )}
    </div>
  );
}

export default ReportsView;
